### ISSUE TITLE
docker-compose up: error on datasource

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/grafana-redis-datasource#15]
![image](https://user-images.githubusercontent.com/753206/86337879-58232c00-bc5a-11ea-985e-cb830c15637c.png)

![image](https://user-images.githubusercontent.com/753206/86337853-4e99c400-bc5a-11ea-824b-c64554786ff6.png)

**Comment by mikhailredis** [comment]
@gkorland We should make it clear in README that you have to build the data source until it will be registered in Grafana and can be automatically installed using `grafana-cli`.
