### ISSUE TITLE
yarn build fail 

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/grafana-redis-datasource#16]
```
⠋ Compiling...  Trace: EACCES: permission denied, open '/home/guy/redisclients/grafana-redis-datasource/dist/module.js'
      at /home/guy/redisclients/grafana-redis-datasource/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/guy/redisclients/grafana-redis-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/guy/redisclients/grafana-redis-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/guy/redisclients/grafana-redis-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:108:69)
✖ EACCES: permission denied, open '/home/guy/redisclients/grafana-redis-datasource/dist/module.js'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikhailredis** [comment]
@gkorland Do you see `dist/` folder created?

Please check permissions for `/home/guy/redisclients/grafana-redis-datasource`. User used to compile the module should have write permission to create `dist` folder.

**Comment by gkorland** [comment]
I have it, but I think I found the cause, it has something to do with the docker-compose:
```bash
git clone git@github.com:RedisTimeSeries/grafana-redis-datasource.git
cd grafana-redis-datasource/
docker-compose up
^c
yarn install 
yarn build
```

**Comment by mikhailredis** [comment]
@gkorland When you started docker-compose before building the data source, it creates `dist/` folder for you looking for the plugin:

```
  grafana:
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-redis-datasource
```

Until we register the data source in the grafana registry, build is required.

**Comment by mikhailredis** [comment]
@gkorland I am going to close this issue. Redis Datasource is available in the official Grafana repository https://grafana.com/grafana/plugins/redis-datasource and won't require to build.
README updated to add instructions on how to use `grafana-cli` to use it.
