### ISSUE TITLE
Redis Datasource is Unsigned. K8S+Helm installation

### ISSUE THREAD

**Issue by misteio** [RedisTimeSeries/grafana-redis-datasource#29]
### Describe the bug
On installation of this plugin, I have an error: 
Failed to load plugin                    logger=plugins error="plugin \"redis-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/redis-datasource/dist

### Version
v1.1.1

### Steps to reproduce
1. Add redis-datasource, on plugins section
2. Relaunch grafana deployment
3. Got an error on log, error="plugin \"redis-datasource\" is unsigned" 

### Expected behavior
It should be installed and visible on my grafana instance.

### Additional context
Grafana is installed on a Kubernetes 1.16 instance, with helm 3.

**Comment by mikhailredis** [comment]
Thanks @misteio for submitting the issue.
I am working with Grafana Labs to sign Redis Datasource v1.1.2 and will let you know when ready.

**Comment by mikhailredis** [comment]
@misteio Redis Datasource v1.1.2 is signed and published on https://grafana.com/grafana/plugins/redis-datasource.
Please try and let me know if you have any questions.

**Comment by misteio** [comment]
It works perfectly now. Thanks a lot for your reactivity and the job you've done.

Have a nice day !
