### ISSUE TITLE
Support codis

### ISSUE THREAD

**Issue by BorisWJ** [RedisTimeSeries/grafana-redis-datasource#32]
can it support codis cluster?

**Comment by gkorland** [comment]
What do you mean by support? which isn't working for you?

**Comment by mikhailredis** [comment]
@BorisWJ Thank you for submitting the issue. Could you please clarify what are you looking for and not working?

Redis datasource supports only Redis connection to port 6379. Sentinel and Cluster API will be introduced in upcoming versions.
