### ISSUE TITLE
Slowlog returns 'No data' for Redis 3.0.6

### ISSUE THREAD

**Issue by wangxin0529** [RedisTimeSeries/grafana-redis-datasource#33]
![image](https://user-images.githubusercontent.com/54661355/89518620-bb7e1c00-d80d-11ea-9871-6eb5cb20d1cf.png)

 `slowlog get` has results

![image](https://user-images.githubusercontent.com/54661355/89518758-f4b68c00-d80d-11ea-98a7-8c0e556c1247.png)

`----------------------------------------------------------------------------------------------------`
if `slowlog get` is empty list
![image](https://user-images.githubusercontent.com/54661355/89518818-0ac44c80-d80e-11ea-9d0d-463c202b3f2f.png)
it will be normal
My Redis version is 3.0.6 ，grafana version is 7.0.3

**Comment by mikhailredis** [comment]
Hello @wangxin0529,

 Thank you for trying the Redis Datasource and the issue. The Slowlog command (https://redis.io/commands/slowlog) was enhanced in Redis version 4 and the command output in version 3 is different.
  I will test on version 3.0.6 and let you know when ready.

**Comment by wangxin0529** [comment]
> Thank you for trying the Redis Datasource and the issue. The Slowlog command (https://redis.io/commands/slowlog) was enhanced in Redis version 4 and the command output in version 3 is different.

OK，I will test on version 4.x

**Comment by marcossv9** [comment]
Hi,

Same issue with Redis 2.8.24 here.

If I run the command from redis-cli it works.

Any help would be appreciated.

Thanks,

**Comment by mikhailredis** [comment]
@wangxin0529 and @marcossv9 the issue is fixed in the master. Please follow BUILD (https://github.com/RedisTimeSeries/grafana-redis-datasource/blob/master/BUILD.md) instructions to build it yourself.

The datasource will be updated in the Grafana repository soon.

**Comment by wangxin0529** [comment]
@mikhailredis When will it could be updated in the Grafana repository？

**Comment by mikhailredis** [comment]
I am finishing the 1.2.0 release with new features and will submit it for review next week.
Can you wait or build it yourself following BUILD instruction meanwhile?
