### ISSUE TITLE
Is it planned/possible to get the stats for clusters too? 

### ISSUE THREAD

**Issue by Doca** [RedisTimeSeries/grafana-redis-datasource#43]
I just discovered your awesome Grafana Dashboard and I wonder if it's also possible to monitor redis clusters with the Datasource plugin/grafana dashboard...

**Comment by mikhailredis** [comment]
Hello @Doca,

  I am glad you discovered it and thank you for the feedback! We are working on the Redis Cluster support and it will be available in the upcoming version.
  I will let you know when ready, stay tuned!

**Comment by Doca** [comment]
So glad to hear that. Do you have a feeling when this will be ready? Just a gut feeling?

**Comment by mikhailredis** [comment]
@Doca,

  Thank you, let's keep it open for tracking cluster support

**Comment by mikhailredis** [comment]
@Doca, Redis Cluster merged to master and will be available in the upcoming version.

![Screen Shot 2020-08-23 at 10 11 13 AM](https://user-images.githubusercontent.com/47795110/90984333-0e074a00-e529-11ea-97a1-59aae2080db0.png)
