### ISSUE TITLE
How to use redis datasource to collect a lot of redis

### ISSUE THREAD

**Issue by wangxin0529** [RedisTimeSeries/grafana-redis-datasource#47]
I have many redis.
How to collect these redis?
Do I have to add multiple data sources?
![image](https://user-images.githubusercontent.com/54661355/90762995-8519c400-e318-11ea-90f7-190c4049954d.png)
one by one?

**Comment by alex6058** [comment]
Hello @wangxin0529 

Yes, you need to add an instance of Datasource for each Redis database you're using. After that, you can use multiple data sources in one dashboard and even in one panel in multiple query mode. Please also note, Grafana template variables support Datasource type, so you can automatically repeat panels and rows for all databases, which you defined. 

Thank you

**Comment by mikhailredis** [comment]
@wangxin0529 you can add Data sources manually as @alex6058 explained or use Data source API to automate: https://grafana.com/docs/grafana/latest/http_api/data_source/

Please let us know if you have any questions.

**Comment by wangxin0529** [comment]
> you can use multiple data sources in one dashboard and even in one panel in multiple query mode.

How to do this？

**Comment by wangxin0529** [comment]
OH, I get it, THANK YOU!

**Comment by mikhailredis** [comment]
@wangxin0529, Unfortunately, this is a limitation of Grafana 7. We can't export the dashboard which supports multiple data sources and share it within datasource.

I have added dashboard which supports multiple Redis instances: https://github.com/RedisTimeSeries/grafana-redis-datasource/blob/master/dashboards/redis.json

Do you want to try and let me know if it works for you?

**Comment by wangxin0529** [comment]
@mikhailredis I use multiple data sources in one dashboard ,and define a variable named server like this
![image](https://user-images.githubusercontent.com/54661355/91399588-cd813680-e870-11ea-9c92-a5b1ad7eb80d.png)
