### ISSUE TITLE
Does it support Azure Cache for Redis?

### ISSUE THREAD

**Issue by mehmetcakmaz** [RedisTimeSeries/grafana-redis-datasource#55]
Hello,

Thank you for great plugin. Does it only work with local redis server or is it available for Azure Cache for Redis?

**Comment by mikhailredis** [comment]
@mehmetcakmaz Thank you for your interest in the plugin. You should be able to connect to any Redis instance. TLS connection is supported as well.

Please let me know if you have trouble connecting to Azure Cache.

**Comment by mikhailredis** [comment]
@mehmetcakmaz Please let me know if you were able to connect to Azure Cache.

**Comment by mehmetcakmaz** [comment]
Thank you for information @mikhailredis 
I will try and notify you within 1 week

**Comment by tbraun-hk** [comment]
Hi @mikhailredis, 

currently, I'm trying the same and had no success so far. I'd like to connect to an instance of "redis cache for grafana". However, I have not been able to find a way of enabling SSL in the grafana plugin for redis.

The "Connection string" shown by Azure is:
"[instance-name].redis.cache.windows.net:6380,password=[base64 encoded password],**ssl=True**,abortConnect=False"

I've copied the base64 encoded password into the "password" field in the redis plugin and tried the following URLs with no success:
- [instance-name].redis.cache.windows.net:6380
- redis://[instance-name].redis.cache.windows.net:6380?ssl=true
- redis://[instance-name].redis.cache.windows.net:6380/?ssl=true

In all cases, the error message was `getInstance error: read tcp [IP]:58070->[IP]:6380: read: connection reset by peer` after a timeout of 15-20 seconds.

I'd be happy to try out other URLs if you've got any ideas. 

Thanks in advance, Tobias

**Comment by mikhailredis** [comment]
@tbraun-hk You don't need to use SSL in the URL, as it's enabled by default as I understand.
Did you provide an SSL authority certificate or enabled Skip to verify?

Meanwhile, I will try to connect to Azure and get back to you shortly.

**Comment by tbraun-hk** [comment]
@mikhailredis thank you very much for the quick reply! Here's a screenshot of my attempt of configuring the plugin, I hope, this is useful to you?
![image](https://user-images.githubusercontent.com/52997644/93889291-501ed980-fce9-11ea-837d-dd5539769c23.png)

**Comment by tbraun-hk** [comment]
OK, here's a success message: After enabling unencrypted access to redis, the plugin is working flawlessly!
![image](https://user-images.githubusercontent.com/52997644/93891123-5c0b9b00-fceb-11ea-9d65-fb5f4de08a48.png)

![image](https://user-images.githubusercontent.com/52997644/93891166-6a59b700-fceb-11ea-8000-342e58225ed4.png)

Still, it would be great to be able to use TLS encryption. Maybe there's a way? 
I really appreciate the time and effort you're making in providing and supporting this plugin, @mehmetcakmaz. Thank you very much!

**Comment by mikhailredis** [comment]
@tbraun-hk Please try to switch "TLS Client Authentication" to enable and provide Authority certificate or enable 'Skip Verify'. Don't need to provide client certificate or key if you don't use them.

**Comment by tbraun-hk** [comment]
@mikhailredis You're right, that setting did it, hooray 👍 
![image](https://user-images.githubusercontent.com/52997644/93892371-c2dd8400-fcec-11ea-958e-281a8e1d6384.png)

Now I've got a redis datasource up and running!

Thank you very much again for your help!

**Comment by mikhailredis** [comment]
@tbraun-hk You are very welcome! Let me know if you need anything else.
