### ISSUE TITLE
Data outside time range in Grafana when doing `TS.MRANGE`

### ISSUE THREAD

**Issue by dpipemazo** [RedisTimeSeries/grafana-redis-datasource#56]
### Describe the bug

When using the `TS.MRANGE` query in grafana we are frequently seeing "Data out of time range" appear. This unfortunately can't be turned off in grafana.

![Screenshot from 2020-08-25 16-51-32](https://user-images.githubusercontent.com/2764032/91239379-3e4f1400-e6f4-11ea-8fd9-cc4bb247d3e4.png)

For the example shown, the graph query and config can be seen here:

![Screenshot from 2020-08-25 16-52-21](https://user-images.githubusercontent.com/2764032/91239442-5f176980-e6f4-11ea-9475-b020ebaf9e55.png)

We're doing a time-based query here over per-process data, i.e. there will be an entry for each process in the system. The issue seems to be coming from when there is a particular process which does not have any data in the given window, but existed at an earlier time:

![Screenshot from 2020-08-25 16-53-15](https://user-images.githubusercontent.com/2764032/91239561-bcabb600-e6f4-11ea-8df0-56211deb43ba.png)

Here, we see that the time window for the query was 16:47 - 16:52 but this `kworker` process which likely only existed well before then returns a single `0` value with a timestamp of `15.46`.

I've verified the query being generated to redis time series is correct (the timestamps are in 5m intervals in the example shown).

![Screenshot from 2020-08-25 16-56-08](https://user-images.githubusercontent.com/2764032/91239613-ebc22780-e6f4-11ea-931a-09ab7401cbd7.png)

### Version

Running:

- Redis `6.04`
- grafana-redis-datasource on commit `d0476c26e67e9737c6039e5c5d03187464b05634`
- Grafana `latest` from Docker Hub.
- Redis Time Series `1.2.7`

### Steps to reproduce

Can actually be reproduced quite effectively through just running our open-source project. Building and launching this will start up a redis, logger that uses `psutil` to parse filesystem stats and log them to redis time series, and a grafana instance with a new-ish build of this plugin

1. Clone the atom repo
```
git clone https://github.com/elementary-robotics/atom/tree/353/metrics_redis_time_series
```
2. Update + init submodules
```
git submodule update --init --recursive
```
3. Build
```
docker-compose -f docker-compose-dev.yml build
```
4. Launch
```
docker-compose -f docker-compose-dev.yml up -d
```

After this, you should be able to log into grafana at `localhost:3001` in your browser and click into any of the dashboards from the home dashboard. The `memory-live` dashboard is the one with this particular graph but it shows up on most of them.

Otherwise please find a `.zip` file with a RDB backup + JSON dashboard configuration that should allow you to reproduce as well.

[redistimeseries.zip](https://github.com/RedisTimeSeries/grafana-redis-datasource/files/5126869/redistimeseries.zip)

### Expected behavior

For some metrics (which are more deterministic, have entries for each time bucket) I do not see this message. Desired behavior is not to see this message.

**Comment by mikhailredis** [comment]
@dpipemazo Thank you for submitting another issue.

Have you tried the same command from `redis-cli` and see the kworker returning 0 for the outside interval? How about remove aggregation?

I will take a look and get back to you.

**Comment by dpipemazo** [comment]
@mikhailredis Thanks for taking a look. I should have confirmed in `redis-cli`, apologies for not doing that originally. I reproduced a similar situation to the graphs above through running:

```
ts.mrange 1598405335639 1598410333697 AGGREGATION avg 1000 WITHLABELS FILTER element=monitor type=process subtype1=cpu_user
```

The full resultant text file is attached and is telling -- the source of the issue is indeed coming from Redis Time Series as we can see some example entries from the query:

```
1484) 1) "monitor:process:99:kworker/7:1:cpu_user"
      2) 1) 1) "element"
            2) "monitor"
         2) 1) "type"
            2) "process"
         3) 1) "container"
            2) "x86_64"
         4) 1) "device"
            2) "default"
         5) 1) "language"
            2) "Python"
         6) 1) "version"
            2) "1.7.2"
         7) 1) "level"
            2) "INFO"
         8) 1) "subtype0"
            2) "99:kworker/7:1"
         9) 1) "subtype1"
            2) "cpu_user"
      3) 1) 1) (integer) 1598456570000
            2) 0
```

and

```
1482) 1) "monitor:process:9866:kworker/3:0:cpu_user"
      2) 1) 1) "element"
            2) "monitor"
         2) 1) "type"
            2) "process"
         3) 1) "container"
            2) "x86_64"
         4) 1) "device"
            2) "default"
         5) 1) "language"
            2) "Python"
         6) 1) "version"
            2) "1.7.2"
         7) 1) "level"
            2) "INFO"
         8) 1) "subtype0"
            2) "9866:kworker/3:0"
         9) 1) "subtype1"
            2) "cpu_user"
      3) 1) 1) (integer) 1598404695000
            2) 0
```

Where we can see for data existing on either side of the time series we are getting a 0 entry back with a timestamp outside of the original range.

I can (and will) file an issue on the Redis Time Series repo about this however I'm not sure it's as straightforward as asking them to do it. This is a debatably reasonable response on their end and I can see use cases where we'd want to know there was something that existed outside of the time range query. It's likely a flag we ask for from them and likely would take a month or so to get in if approved?

I do think given how this "Data outside of time range" cannot be turned off in grafana and materially impacts the usability of the graphs it would be nice to clip any time values returned from redis to (min, max) on the time series queried. That would solve this pretty easily I think without too much effort.

Full output of the mrange query attached below. 

[mrange.txt](https://github.com/RedisTimeSeries/grafana-redis-datasource/files/5131034/mrange.txt)

**Comment by mikhailredis** [comment]
@dpipemazo Thank you for confirming, I am checking with the RedisTimeSeries team what will be the expected behavior in this case.

I agree that extra intervals can be clipped in the plug-in, but I expect RedisTimeSeries to return the correct values.

**Comment by dpipemazo** [comment]
I did go ahead and file the issue on the Redis Time Series repo as well: https://github.com/RedisTimeSeries/RedisTimeSeries/issues/506

**Comment by mikhailredis** [comment]
@dpipemazo Thank you, let's wait for the RedisTimeSeries team response.

**Comment by mikhailredis** [comment]
@dpipemazo RedisTimeSeries team accepted the issue and will work on it.

Do you mind to close this issue and follow it in RedisTimeSeries?

**Comment by dpipemazo** [comment]
Sure, thanks for helping to bring it to their attention.
