### ISSUE TITLE
Support Connecting to Redis via Unix Socket

### ISSUE THREAD

**Issue by dpipemazo** [RedisTimeSeries/grafana-redis-datasource#58]
### Is your enhancement related to a problem? Please describe.

It would be nice to support connecting to and querying redis via a unix socket. We use this form of communicating with Redis frequently at Elementary since we run redis on the edge on our robots. We are currently spinning up our grafana server also on the edge for local development and it makes our `docker-compose` configuration cleaner if we don't have to map ports onto the host or assume container/service names.

### Describe the solution you'd like

Allow for something like below:

![Screenshot from 2020-08-27 12-03-26](https://user-images.githubusercontent.com/2764032/91483992-5aba9000-e85d-11ea-8d8c-7cca358e8471.png)

### Describe alternatives you've considered

We can (and currently do) support connection via TCP. When running grafana in its own container though the data source either needs to be:

1. `localhost:port`, in which case we need to map the port from the redis container onto the host machine. This adds a potentially preventable port mapping
2. `container_name:port` in which case we're hardcoding a dependency that our redis is launched with a certain container name which is not ideal. 

Thanks for taking a look and apologies for filing so many issues in the past week or so. The grafana integration is really fantastic as-is and this would just make it a bit better for us. I do realize this is a fairly niche use case.

**Comment by mikhailredis** [comment]
@dpipemazo Redis Data Source based on Radix golang client (https://github.com/mediocregopher/radix). I don't see an option to connect using the Unix Socket at first sight. If it will be supported by Radix, it would be ideal.

I can take a closer look later, but you can ask Radix developer if it's something he would be interested to implement. I see that some Redis clients support connecting using a Unix socket.

**Comment by dpipemazo** [comment]
Yes, I agree it should come from the client. We've been using `redis-py` and `hiredis` via the unix socket for a while with good success, makes sense this support isn't in all of the language clients, particularly a language like golang which is really geared at networked connections. I'll file an issue over there. Thanks!

**Comment by mikhailredis** [comment]
@dpipemazo Thank you. Please put it here as well for tracking.

**Comment by dpipemazo** [comment]
Issue [filed on radix](https://github.com/mediocregopher/radix/issues/231)

**Comment by mikhailredis** [comment]
@dpipemazo Thank you for submitting the issue for radix. Looks like we found the way how we can add Socket connection as an additional client type.
I will test and let you know later tonight.

**Comment by mikhailredis** [comment]
@dpipemazo Let me add additional Client type for socket connection and will send you branch to try. Give me 15 minutes.

**Comment by dpipemazo** [comment]
@mikhailredis thank you! This is very quick and much appreciated.

**Comment by mikhailredis** [comment]
@dpipemazo Please verify and let me know if it works for you: https://github.com/RedisTimeSeries/grafana-redis-datasource/tree/feat/socket

**Comment by dpipemazo** [comment]
Thanks! Trying now :+1:

**Comment by dpipemazo** [comment]
Works great! :tada: 

![Screenshot from 2020-08-27 20-34-15](https://user-images.githubusercontent.com/2764032/91518256-b78d6900-e8a4-11ea-84ff-9ad7e46cae6f.png)

Thank you!!

**Comment by mikhailredis** [comment]
@dpipemazo Merged to master. Please let me know if there is anything else!
