### ISSUE TITLE
Plugin health check failed for ARM on Linux

### ISSUE THREAD

**Issue by fcafagna** [RedisTimeSeries/grafana-redis-datasource#61]
Hi, 

I would like to setup a redisTimeSeries server to be monitored by a Grafana interface, on a raspberry PI. 
I was able to install a Grafana instance and a redis server. 
I installed and loaded the RedisTimeSeries module and the redis-datasource plugin. 
When I create the data source in Grafana and Save&Test it, I get a Plugin health check failed error. 
### Describe the bug
When I create the data source in Grafana and Save&Test it, I get a Plugin health check failed error. 
The datasource is saved but no actual connection is executed
### Version
I am running a Raspbian GNU/Linux 10 (buster), on a Raspberry Pi4
The Grafana version is the v7.1.5 (9893b8c53d) (installed via apt)
The redis version (from INFO command): 
redis_version:6.0.7
redis_git_sha1:dbea5f7a
redis_git_dirty:0
redis_build_id:dfdff42c1b78b208
redis_mode:standalone
os:Linux 5.4.51-v7l+ armv7l
arch_bits:32
Redis is using the standard port: 6379
RedisTimeSeries, is the latest version cloned from the github repository. 
redis-datasource plugin, is the v 1.2.0, installed via grafana-cli (I used the grafana user to install the plugin)

### Steps to reproduce
Just try to create a datasource in a Grafana vanilla installation. 
### Additional context

thanks a lot in advance for your help. 
Francesco

**Comment by mikhailredis** [comment]
Hello @fcafagna, unfortunately, Linux 32bit for Arm v7l is not included in the Redis Data Source.
There are two options to run Data Source on Raspberry Pi:
 1) Install 64bit Linux like Debian and install Redis Data Source using grafana-cli. We included ARM64 Linux build in the latest version 1.2.0.
 2) I can create a branch with a 32bit Linux version or you can build it yourself and then install it following the BUILD instructions.

Please let me know what option works for you.

**Comment by fcafagna** [comment]
Ciao @mikhailredis , 
thanks a lot for you prompt reply. 
The Rpi 4 is a 64bit platform, but the 64bit Raspbian OS is still in beta, unstable, version. 
So I will try to built a 32bit version and let you know. 
Cheers, 
Francesco

**Comment by mikhailredis** [comment]
@fcafagna, it's not that easy to build a 32bit version as you will need to modify `grafana-plugin-sdk-go`/build/common.go to support the new architecture. 

Could you please take a look at grafana log file and let me know what is the executable name Grafana is looking for? Is it "redis-datasource_linux_arm32" or something else.

**Comment by mikhailredis** [comment]
@fcafagna I created a branch with Linux for ARM executable, https://github.com/RedisTimeSeries/grafana-redis-datasource/archive/feat/arm.zip.

Please download and install following the BUILD instructions and let me know if it works for you.

**Comment by fcafagna** [comment]
Ciao @mikhailredis , 
thanks a lot. I will try to build it as soon as I can and let you know. 
By the way, Grafana is looking for the executable: "redis-datasource_linux_arm"
Cheers
Francesco

**Comment by fcafagna** [comment]
Ciao @mikhailredis,
I tried to build the module, but I am experiencing an odd behavior with GO. 
While I had no problem building the React frontend, I am problem with the go part. 
Namely, when I try to install the Grafana SDK: 
 go get -u -v github.com/grafana/grafana-plugin-sdk-go
I get the error:
go get: error loading module requirements
The error is random. Is not always issued for the same packet. Sometimes I get the error after several package updates, sometimes after few ones. Anyway the behavior is random. 
So when I try to build with: mage -v
I got some error of package unavailable like this:
../../go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:36:2: unknown import path "golang.org/x/net/trace": cannot find module providing package golang.org/x/net/trace
I tried to manually install the modules using:
go get -u golang.org/x/net/trace
But then I get an error:
go get golang.org/x/net/trace: no matching versions for query "latest"
I suppose I have to specify a version instead of using the default one. 

Thanks a lot in advance for your support. 
Cheers, 
Francesco

**Comment by mikhailredis** [comment]
@fcafagna You may miss my last reply, you don't need to build anything yourself. I created a branch with Linux for ARM executable, https://github.com/RedisTimeSeries/grafana-redis-datasource/archive/feat/arm.zip.

Just download and install it following BUILD instructions. Golang installation can be tricky and depends on your environment.

**Comment by fcafagna** [comment]
Ciao @mikhailredis , 

sorry I misunderstood. I haven't noticed the executable. 
Now is working fine. I can connect to the Redis instance and I can see the dashboards. 
Thanks a lot for the help!! I really appreciated it. 
Cheers, 
Francesco

**Comment by mikhailredis** [comment]
Thank you for the update @fcafagna.
I will include the ARM release to the upcoming version of Data Source.

**Comment by mikhailredis** [comment]
Pull request to Grafana Plugin SDK opened to include ARM build: https://github.com/grafana/grafana-plugin-sdk-go/pull/224
