### ISSUE TITLE
Timeseries data time stamp truncated to seconds

### ISSUE THREAD

**Issue by lhh31** [RedisTimeSeries/grafana-redis-datasource#64]
Using the timeseries commands to perform tasks.range queries the corresponding data frame built has the milliseconds truncated.

Reviewing the code this makes sense as the conversion from epoch to go time object using time.Unix has nanoseconds set to zero and seconds value divided by 1000.

There may be a reason for this, but effectively this means that data at higher resolutions than 1 second are displayed at the same time point.

If someone could please confirm if this is by design or an improvement that could be made?

**Comment by mikhailredis** [comment]
@lhh31 Thank you for submitting the issue. You are correct, RedisTimeSeries ts.range and ts.mrange commands return milliseconds and we can actually convert to time.Unix using nanoseconds as converted milliseconds.
```
  ts := time.Unix(0, t*int64(time.Millisecond))
```

**Comment by mikhailredis** [comment]
@lhh31 Fix merged to the master branch and will be available in the next release. Meanwhile, you can test and build yourself following BUILD instructions.
Please let me know if you have any questions.

**Comment by lhh31** [comment]
@mikhailredis Confirmed that the latest master branch works down to millisecond resolution. Thanks for the quick response.

**Comment by mikhailredis** [comment]
@lhh31 Thank you for submitting and verifying the issue.
Please let us know if you see anything else.
