### ISSUE TITLE
Redis Datasource Plugin Failing Health Check on Grafana

### ISSUE THREAD

**Issue by WPS63** [RedisTimeSeries/grafana-redis-datasource#71]
## Summary
I am trying to connect my Redis server to Grafana using the plugin and am getting a plugin health check failure message when I try to save and test my datasource.
## Relevant information
My Redis server is running locally on the default localhost and port(127.0.0.1:6379.) I have installed the plugin and can see it on my list of available plugins on the Grafana dashboard as well as through the grafana-cli command. I have tried many url combinations(such as localhost:6379/0, http://localhost:6379, 127.0.0.1:6379, etc.) and had no luck. Here is an image of the dashboard page that is causing the issue: 

![pluginhealth1](https://user-images.githubusercontent.com/53489016/95493931-27464780-096b-11eb-98f5-c9cd14ad51b0.png)

Thanks in advance for your help and guidance.

**Comment by mikhailredis** [comment]
Hello @WPS63, thank you for submitting the issue.

What platform do you use? Could you please take a look at Grafana log files and send me an error. It does not look like a Redis error, more like a communication error between Grafana and Plug-in.

**Comment by WPS63** [comment]
Hi Mikhail,
I am using Raspbian OS. Here is the request and the error from my Grafana log file: 

t=2020-10-08T13:01:57-0400 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/5/health status=500 remote_addr=[::1] time_ms=67 size=40 referer=http://localhost:3000/datasources/edit/5/
t=2020-10-08T13:02:02-0400 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="Failed to check plugin health: Health check failed" remote_addr=[::1]

**Comment by mikhailredis** [comment]
@WPS63 Raspbian OS is 32bit and unfortunately, 32bit ARM Linux executable is not included in the release 1.2.0 available in the Grafana repository.
This issue was requested in #61, we updated the Grafana SDK, and it will be a part of the upcoming release 1.2.1.

I just built the master with 32bit ARM Linux executable for you: https://github.com/RedisTimeSeries/grafana-redis-datasource/archive/feat/71-arm.zip
Please download and install it following BUILD instructions. Let me know if it works for you.

**Comment by WPS63** [comment]
It worked perfectly. Thank you very very much, sir.

**Comment by mikhailredis** [comment]
@WPS63 Thank you for the update. Please let me know if you need anything else.
