### ISSUE TITLE
TimeSeries timestamp seems to be truncated by plugin

### ISSUE THREAD

**Issue by johnkbarrow** [RedisTimeSeries/grafana-redis-datasource#75]
### Describe the bug
I am a noob so if this is not a bug but user error then I apologise in advance.
I am adding data to a timeseries. The data looks correct when queried using redis-cli, but when i try to query using the grafana plugin, it appears that the timestamps are being truncated so that the date shows way in the past.
e.g.
from redis-cli:
> ts.get order:revenue
1) (integer) 1602675285 (which translates to 14 October 2020 11:34:45)
2) 3927.09

from grafana query inspector:
time
value
1970-01-19 14:11:15
3927

If you convert "1970-01-19 14:11:15" into an integer it's 1602675 which is the first 7 values of the value in the database.
### Version

plugin version 1.2.0
grafana version 7.2.1
hosted redis version 6.0.5
RedisTimeSeries Ver 1.2.7

**Comment by mikhailredis** [comment]
Hello @johnkbarrow, thank you for submitting the issue.

  Could you please send me screenshot how do you display it? I just tried on TimeSeries 1.2, 1.4 and everything works as expected:
![Screen Shot 2020-10-14 at 7 18 36 AM](https://user-images.githubusercontent.com/47795110/96002086-95688f80-0ded-11eb-9f59-08df04260d10.png)

**Comment by johnkbarrow** [comment]
Hi @mikhailredis - thanks for the quick reply. I figured out my mistake - I was entering the timestamps into the timeseries as seconds rather than milliseconds. Now working as expected.
Thanks again.

**Comment by miohtama** [comment]
@johnkbarrow Thank you for reporting this out. I fell into this same trap by using the standard UNIX timestamp and RedisTimeseries did not warn about it at any point. I did not notice the mistake until the data was imported to Grafana.
